spring.application.name=canvas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/canvas}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/canvas}
server.port=8080
